import { createContext } from 'react';

export const PlayingContext = createContext({
  footImg: undefined,
  footTitle: undefined,
  indexSongs: undefined,
  countSongs: [],
  valueVol: undefined,
  playingSong: [],
  playingQueue: [],
  isPlaying: false,
  progress: false,
  playListSong: [],
  NewNamePlaylist: undefined,
  addSongToQueue: () => {},
  addQueue: () => {},
  deleteQueue: () => {},
  setPlaying: () => {},
  playSong: () => {},
  SetvalueVol: () => {},
  setPlayingQueue: () => {},
  setIndex: () => {},
  setProgress: () => {},
  setCountSongs: () => {},
  setPlayListSongs: () => {},
  setFootImg: () => {},
  setFootTitle: () => {},
  setNewNamePlaylist: () => {},
});
